### ISSUE TITLE
嘤qwq

### ISSUE THREAD

**Issue by CharlotteFallices** [Mabbs/MayxDaily#1]
访问不了了诶QAQ
![image](https://user-images.githubusercontent.com/47619464/107906478-2f9f3680-6f8c-11eb-93c5-a628a7edd085.png)

**Comment by Mabbs** [comment]
> 访问不了了诶QAQ
> ![image](https://user-images.githubusercontent.com/47619464/107906478-2f9f3680-6f8c-11eb-93c5-a628a7edd085.png)

唉，域名忘记续了，只能用github的域名了：<https://mabbs.github.io/MayxDaily>
